#version 430

layout(local_size_x = 1, local_size_y = 1) in;

layout(binding = 0, r32f) uniform writeonly image2D outHeight;

uniform ivec2 size;
uniform vec2 chunkOffset;
uniform float texelWorld;
uniform float baseFreq;
uniform int octaves;
uniform float lacunarity;
uniform float gain;
uniform float amplitude;
uniform float seed;


#include "noise.glsl"

#define OCTAVES 6

float fbm (vec2 coordinate) {
    coordinate = coordinate * 2.0 - 1.0;
    // Initial values
    float value = 0.0;
    float amplitude = 1.0;
    float frequency = 1.0;
    float weights = 0.0;

    // Loop of octaves
    for (int i = 0; i < OCTAVES; i++)
    {
        vec2 sample_coordinates = (frequency * 1.0 * coordinate) + (frequency * 1);
        value += amplitude * (0.5 + 0.5 * snoise(sample_coordinates));
        weights += amplitude;
        frequency *= 0.5;
        amplitude *= 1.5;
    }

    float height = value / weights;
    return pow(height, 1);
}

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);

    vec2 worldXY = chunkOffset + vec2(gid) * texelWorld;

    float h = fbm(worldXY) * amplitude;

    imageStore(outHeight, gid, vec4(h, 0, 0, 1));
}
